source 'https://rubygems.org'
gem 'sinatra'
gem 'sqlite3' # For ActiveRecord's sqlite support (I think)
gem 'activerecord'
gem 'sinatra-flash'
gem 'slim'
gem 'sass'
gem 'mini_magick'
gem 'rack_csrf'
gem 'mimemagic'
